---
checks:
  - name: 'welcome'
    title: 'Welcome to TeamCI'
    image: 'teamci/welcome'
    summary: 'How to use TeamCI'
  - name: 'rubocop'
    title: 'Rubocop'
    image: 'teamci/rubocop'
    summary: 'Ruby code linting'
  - name: 'editorconfig'
    title: 'Editorconfig'
    image: 'teamci/editorconfig'
    summary: All files covered by `.editorconfig` rules
