#!/usr/bin/env bash

set -euo pipefail

declare scratch
scratch="$(mktemp)"

while read -r file; do
	if head -n 1 "${file}" | grep -qF 'bash'; then
		echo "${file}" >> "${scratch}"
	fi
done

# Ignore fixtures in teamci/builder
grep -vF 'fixtures' "${scratch}"
